= torf-cli

torf-cli is a command line tool that can create torrents and magnet links, dump
the metainfo of a torrent, and edit existing torrents (e.g.  to fix a typo
without having to hash all the pieces again).

The output is pleasant to read for humans and easy to parse with common CLI
tools if stdout is not a TTY.

An optional configuration file specifies custom default options and profiles
that give names to sets of options.

Documentation is available as a man page (see <<Installation>>), or you can
https://rndusr.github.io/torf-cli/torf.1.html[read it here].

The only depdencies are https://pypi.org/project/torf/[torf] and
https://pypi.org/project/pyxdg/[pyxdg].


== Examples

Create private torrent with two trackers::

[source,sourceCode,sh]
----
$ torf ./docs -t http://bar:123/announce -t http://baz:321/announce --private
       Name  docs
       Size  60.1 KiB
    Created  2018-06-19 14:47:26
    Private  yes
   Trackers  http://bar:123/announce
             http://baz:321/announce
 Piece Size  16 KiB
Piece Count  4
 File Count  3
      Files  docs
             ├─torf.1
             ├─torf.1.asciidoc
             └─torf.1.html
       Path  docs
   Progress  100.00 %  |  Time: 0:00:00  |  58.84 MB/s
  Info Hash  215f506179b6526b582e4fb78ebc24dd1f2a791f
     Magnet  magnet:?xt=urn:btih:215f506179b6526b582e4fb78ebc24dd1f2a791f&dn=docs&xl=61542&tr=http%3A%2F%2Fbar%3A123%2Fannounce&tr=http%3A%2F%2Fbaz%3A321%2Fannounce
    Torrent  docs.torrent
----

Display metainfo of an existing torrent::

[source,sourceCode,sh]
----
$ torf -i docs.torrent
       Name  docs
  Info Hash  215f506179b6526b582e4fb78ebc24dd1f2a791f
       Size  60.1 KiB
    Created  2018-06-19 14:47:26
    Private  yes
   Trackers  http://bar:123/announce
             http://baz:321/announce
 Piece Size  16 KiB
Piece Count  4
 File Count  3
      Files  docs
             ├─torf.1
             ├─torf.1.asciidoc
             └─torf.1.html
     Magnet  magnet:?xt=urn:btih:215f506179b6526b582e4fb78ebc24dd1f2a791f&dn=docs&xl=61542&tr=http%3A%2F%2Fbar%3A123%2Fannounce&tr=http%3A%2F%2Fbaz%3A321%2Fannounce
----

Quickly add a comment to an existing torrent::

[source,sourceCode,sh]
----
$ torf -i docs.torrent --comment 'Forgot to add this comment.' -o docs.revised.torrent
       Name  docs
  Info Hash  215f506179b6526b582e4fb78ebc24dd1f2a791f
       Size  60.1 KiB
    Comment  Forgot to add this comment.
    Created  2018-06-19 14:47:26
    Private  yes
   Trackers  http://bar:123/announce
             http://baz:321/announce
 Piece Size  16 KiB
Piece Count  4
 File Count  3
      Files  docs
             ├─torf.1
             ├─torf.1.asciidoc
             └─torf.1.html
     Magnet  magnet:?xt=urn:btih:215f506179b6526b582e4fb78ebc24dd1f2a791f&dn=docs&xl=61542&tr=http%3A%2F%2Fbar%3A123%2Fannounce&tr=http%3A%2F%2Fbaz%3A321%2Fannounce
    Torrent  docs.revised.torrent
----

Get a list of files::

[source,sourceCode,sh]
----
$ torf -i docs.revised.torrent | grep '^Files' | cut -f2-
docs/torf.1     docs/torf.1.asciidoc    docs/torf.1.html
----


== Installation

The latest release is available on https://pypi.org/project/torf-cli[PyPI] and
on https://aur.archlinux.org/packages/python-torf-cli/[AUR].


=== pipsi

The easiest and cleanest installation method is
https://pypi.org/project/pipsi/[pipsi], which installs each application with all
dependencies in a separate virtual environment in `~/.local/venvs/` and links
the executable to `~/.local/bin/`.

[source,sourceCode,sh]
----
$ pipsi install torf-cli
$ pipsi uninstall torf-cli
----

The only drawback is that, at the time of writing, pipsi doesn't make the man
page available.  But you can just
https://rndusr.github.io/torf-cli/torf.1.html[read it in your browser].


=== pip

The alternative is regular https://pypi.org/project/torf/[pip]:

[source,sourceCode,sh]
----
$ pip3 install torf-cli         # Installs system-wide (/usr/local/)
$ pip3 install --user torf-cli  # Installs in your home (~/.local/)
----

The https://github.com/rndusr/torf-cli[latest development version] is available
on GitHub in the master branch.

[source,sourceCode,sh]
----
$ pip3 install [--user] git+https://github.com/rndusr/torf-cli.git
----


== Contributing

Bug reports and feature requests are welcome in the
https://github.com/rndusr/torf-cli/issues[issue tracker].


== License

torf-cli is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
https://www.gnu.org/licenses/gpl-3.0.txt[GNU General Public License] for
more details.
